(base) ]0;~/universal/templates[01;34m~/universal/templates[00m$ [K(base) ]0;~/universal/templates[01;34m~/universal/templates[00m$ python app.py
python: can't open file 'app.py': [Errno 2] No such file or directory
(base) ]0;~/universal/templates[01;34m~/universal/templates[00m$ p[[K[Kpyht[K[Kthon3 app.py[1P[1P[K(base) ]0;~/universal/templates[01;34m~/universal/templates[00m$ thon3 app.py[1@p
bash: pthon3: command not found
(base) ]0;~/universal/templates[01;34m~/universal/templates[00m$ pthon3 app.pyython[C[C[C[C[C[C[C\[K
python: can't open file 'app.py': [Errno 2] No such file or directory
(base) ]0;~/universal/templates[01;34m~/universal/templates[00m$ cd ..
(base) ]0;~/universal[01;34m~/universal[00m$ cd ..python app.py\[K
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Serving Flask app "app" (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://172.17.0.2:12345/ (Press CTRL+C to quit)
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
127.0.0.1 - - [02/Jul/2021 03:58:50] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 03:58:55] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get?msg=Hi+I+am+tired HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 03:58:56] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get?msg=Hi+I+am+tired HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 03:59:24] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 03:59:26] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get?msg=Hi+I+am+tired HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 03:59:27] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get?msg=Hi+I+am+tired HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 03:59:31] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get?msg=Hi+I+am+tired HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 04:00:20] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 04:00:22] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get?msg=Hi+I+am+tired HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 04:00:23] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get?msg=Hi+I+am+tired HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 04:00:24] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get?msg=Hi+I+am+tired HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 04:00:33] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get?msg=Hi+I+am+tired HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 04:00:34] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get?msg=Hi+I+am+tired HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 04:00:34] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get?msg=Hi+I+am+tired HTTP/1.1" 200 -
 * Detected change in '/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py', reloading
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
 * Detected change in '/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py', reloading
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
 * Detected change in '/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py', reloading
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
 * Detected change in '/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py', reloading
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
 * Detected change in '/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py', reloading
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
 * Detected change in '/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py', reloading
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
 * Detected change in '/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py', reloading
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
 * Detected change in '/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py', reloading
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
 * Detected change in '/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py', reloading
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
 * Detected change in '/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py', reloading
 * Restarting with stat
^CTraceback (most recent call last):
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py", line 23, in <module>
    model_bot2human = AutoModelForCausalLM.from_pretrained("saved_model")
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 381, in from_pretrained
    return model_class.from_pretrained(pretrained_model_name_or_path, *model_args, config=config, **kwargs)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1205, in from_pretrained
    state_dict = torch.load(resolved_archive_file, map_location="cpu")
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/torch/serialization.py", line 592, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/torch/serialization.py", line 851, in _load
    result = unpickler.load()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/torch/serialization.py", line 843, in persistent_load
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/torch/serialization.py", line 831, in load_tensor
    storage = zip_file.get_storage_from_record(name, size, dtype).storage()
KeyboardInterrupt
(base) ]0;~/universal[01;34m~/universal[00m$ python app.py
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Serving Flask app "app" (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://172.17.0.2:12345/ (Press CTRL+C to quit)
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
127.0.0.1 - - [02/Jul/2021 04:18:32] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
 * Detected change in '/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py', reloading
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
 * Detected change in '/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py', reloading
 * Restarting with stat
^CTraceback (most recent call last):
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py", line 23, in <module>
    model_bot2human = AutoModelForCausalLM.from_pretrained("saved_model")
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 381, in from_pretrained
    return model_class.from_pretrained(pretrained_model_name_or_path, *model_args, config=config, **kwargs)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1173, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 846, in __init__
    self.transformer = GPT2Model(config)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 581, in __init__
    self.h = nn.ModuleList([GPT2Block(config) for _ in range(config.num_hidden_layers)])
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 581, in <listcomp>
    self.h = nn.ModuleList([GPT2Block(config) for _ in range(config.num_hidden_layers)])
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 302, in __init__
    self.mlp = GPT2MLP(inner_dim, config)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 275, in __init__
    self.c_fc = Conv1D(intermediate_size, embed_dim)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1394, in __init__
    nn.init.normal_(w, std=0.02)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/torch/nn/init.py", line 141, in normal_
    return _no_grad_normal_(tensor, mean, std)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/torch/nn/init.py", line 19, in _no_grad_normal_
    return tensor.normal_(mean, std)
KeyboardInterrupt
(base) ]0;~/universal[01;34m~/universal[00m$ python app.py
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Serving Flask app "app" (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://172.17.0.2:12345/ (Press CTRL+C to quit)
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
127.0.0.1 - - [02/Jul/2021 04:20:10] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 04:20:12] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
 * Detected change in '/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py', reloading
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
127.0.0.1 - - [02/Jul/2021 04:21:19] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
 * Detected change in '/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py', reloading
 * Restarting with stat
^C(base) ]0;~/universal[01;34m~/universal[00m$ python app.py
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Serving Flask app "app" (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://172.17.0.2:12345/ (Press CTRL+C to quit)
 * Restarting with stat
^CTraceback (most recent call last):
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py", line 23, in <module>
    model_bot2human = AutoModelForCausalLM.from_pretrained("saved_model")
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 381, in from_pretrained
    return model_class.from_pretrained(pretrained_model_name_or_path, *model_args, config=config, **kwargs)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1173, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 846, in __init__
    self.transformer = GPT2Model(config)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 581, in __init__
    self.h = nn.ModuleList([GPT2Block(config) for _ in range(config.num_hidden_layers)])
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 581, in <listcomp>
    self.h = nn.ModuleList([GPT2Block(config) for _ in range(config.num_hidden_layers)])
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 295, in __init__
    self.attn = GPT2Attention(config)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 154, in __init__
    self.c_attn = Conv1D(3 * self.embed_dim, self.embed_dim)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1394, in __init__
    nn.init.normal_(w, std=0.02)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/torch/nn/init.py", line 141, in normal_
    return _no_grad_normal_(tensor, mean, std)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/torch/nn/init.py", line 19, in _no_grad_normal_
    return tensor.normal_(mean, std)
KeyboardInterrupt
(base) ]0;~/universal[01;34m~/universal[00m$ python app.py
^CTraceback (most recent call last):
  File "app.py", line 23, in <module>
    model_bot2human = AutoModelForCausalLM.from_pretrained("saved_model")
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 381, in from_pretrained
    return model_class.from_pretrained(pretrained_model_name_or_path, *model_args, config=config, **kwargs)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1173, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 846, in __init__
    self.transformer = GPT2Model(config)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 577, in __init__
    self.wte = nn.Embedding(config.vocab_size, self.embed_dim)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 138, in __init__
    self.reset_parameters()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 147, in reset_parameters
    init.normal_(self.weight)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/torch/nn/init.py", line 141, in normal_
    return _no_grad_normal_(tensor, mean, std)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/torch/nn/init.py", line 19, in _no_grad_normal_
    return tensor.normal_(mean, std)
KeyboardInterrupt

(base) ]0;~/universal[01;34m~/universal[00m$ python app.py
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Serving Flask app "app" (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://172.17.0.2:12345/ (Press CTRL+C to quit)
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
127.0.0.1 - - [02/Jul/2021 04:22:26] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
^C(base) ]0;~/universal[01;34m~/universal[00m$ python app.py
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Serving Flask app "app" (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://172.17.0.2:12345/ (Press CTRL+C to quit)
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
127.0.0.1 - - [02/Jul/2021 04:23:52] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 04:23:55] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 04:23:56] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 04:23:57] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
 * Detected change in '/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py', reloading
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
^C(base) ]0;~/universal[01;34m~/universal[00m$ python app.py
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Serving Flask app "app" (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://172.17.0.2:12345/ (Press CTRL+C to quit)
 * Restarting with stat
^CTraceback (most recent call last):
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py", line 23, in <module>
    model_bot2human = AutoModelForCausalLM.from_pretrained("saved_model")
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 381, in from_pretrained
    return model_class.from_pretrained(pretrained_model_name_or_path, *model_args, config=config, **kwargs)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1173, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 846, in __init__
    self.transformer = GPT2Model(config)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 581, in __init__
    self.h = nn.ModuleList([GPT2Block(config) for _ in range(config.num_hidden_layers)])
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 581, in <listcomp>
    self.h = nn.ModuleList([GPT2Block(config) for _ in range(config.num_hidden_layers)])
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 295, in __init__
    self.attn = GPT2Attention(config)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 154, in __init__
    self.c_attn = Conv1D(3 * self.embed_dim, self.embed_dim)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1394, in __init__
    nn.init.normal_(w, std=0.02)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/torch/nn/init.py", line 141, in normal_
    return _no_grad_normal_(tensor, mean, std)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/torch/nn/init.py", line 19, in _no_grad_normal_
    return tensor.normal_(mean, std)
KeyboardInterrupt
(base) ]0;~/universal[01;34m~/universal[00m$ python app.py
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Serving Flask app "app" (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
Traceback (most recent call last):
  File "app.py", line 86, in <module>
    app.run(host = '0.0.0.0', port = port, debug=True)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 982, in run_simple
    s.bind(server_address)
OSError: [Errno 98] Address already in use
(base) ]0;~/universal[01;34m~/universal[00m$ python app.py
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Serving Flask app "app" (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://172.17.0.2:12345/ (Press CTRL+C to quit)
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
127.0.0.1 - - [02/Jul/2021 04:44:13] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 04:44:17] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 04:44:21] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 04:44:53] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 04:44:55] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 04:44:56] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 04:45:50] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
 * Detected change in '/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py', reloading
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
 * Detected change in '/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py', reloading
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
 * Detected change in '/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py', reloading
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
 * Detected change in '/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py', reloading
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
^C(base) ]0;~/universal[01;34m~/universal[00m$ 
(base) ]0;~/universal[01;34m~/universal[00m$ python app.py[8Pcd ..python app.py
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Serving Flask app "app" (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://172.17.0.2:12345/ (Press CTRL+C to quit)
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
127.0.0.1 - - [02/Jul/2021 04:49:44] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 04:49:47] "[35m[1mGET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get?flag=2 HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py", line 47, in get_bot2bot_response
    return respond_bot2bot()
TypeError: respond_bot2bot() missing 1 required positional argument: 'flag'
127.0.0.1 - - [02/Jul/2021 04:49:49] "[35m[1mGET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get?flag=2 HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py", line 47, in get_bot2bot_response
    return respond_bot2bot()
TypeError: respond_bot2bot() missing 1 required positional argument: 'flag'
127.0.0.1 - - [02/Jul/2021 04:49:50] "[35m[1mGET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get?flag=2 HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py", line 47, in get_bot2bot_response
    return respond_bot2bot()
TypeError: respond_bot2bot() missing 1 required positional argument: 'flag'
127.0.0.1 - - [02/Jul/2021 04:49:50] "[35m[1mGET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get?flag=2 HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py", line 47, in get_bot2bot_response
    return respond_bot2bot()
TypeError: respond_bot2bot() missing 1 required positional argument: 'flag'
127.0.0.1 - - [02/Jul/2021 04:49:50] "[35m[1mGET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get?flag=2 HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py", line 47, in get_bot2bot_response
    return respond_bot2bot()
TypeError: respond_bot2bot() missing 1 required positional argument: 'flag'
127.0.0.1 - - [02/Jul/2021 04:49:51] "[35m[1mGET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get?flag=2 HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py", line 47, in get_bot2bot_response
    return respond_bot2bot()
TypeError: respond_bot2bot() missing 1 required positional argument: 'flag'
127.0.0.1 - - [02/Jul/2021 04:49:51] "[35m[1mGET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get?flag=2 HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py", line 47, in get_bot2bot_response
    return respond_bot2bot()
TypeError: respond_bot2bot() missing 1 required positional argument: 'flag'
127.0.0.1 - - [02/Jul/2021 04:50:02] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 04:50:03] "[35m[1mGET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py", line 47, in get_bot2bot_response
    return respond_bot2bot()
TypeError: respond_bot2bot() missing 1 required positional argument: 'flag'
127.0.0.1 - - [02/Jul/2021 04:50:04] "[35m[1mGET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py", line 47, in get_bot2bot_response
    return respond_bot2bot()
TypeError: respond_bot2bot() missing 1 required positional argument: 'flag'
127.0.0.1 - - [02/Jul/2021 04:50:05] "[35m[1mGET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py", line 47, in get_bot2bot_response
    return respond_bot2bot()
TypeError: respond_bot2bot() missing 1 required positional argument: 'flag'
127.0.0.1 - - [02/Jul/2021 04:50:05] "[35m[1mGET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py", line 47, in get_bot2bot_response
    return respond_bot2bot()
TypeError: respond_bot2bot() missing 1 required positional argument: 'flag'
 * Detected change in '/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py', reloading
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
127.0.0.1 - - [02/Jul/2021 04:50:24] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 04:50:24] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 04:50:26] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 04:50:27] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
 * Detected change in '/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py', reloading
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
127.0.0.1 - - [02/Jul/2021 04:53:31] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 04:53:35] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
 * Detected change in '/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py', reloading
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
 * Detected change in '/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py', reloading
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
 * Detected change in '/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py', reloading
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
127.0.0.1 - - [02/Jul/2021 04:55:14] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 04:55:17] "[35m[1mGET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2127, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a Tensor.
127.0.0.1 - - [02/Jul/2021 04:55:19] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 04:55:22] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 04:55:24] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 04:55:26] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 04:55:28] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 04:55:30] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 04:55:33] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 04:55:35] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 04:55:37] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
^C(base) ]0;~/universal[01;34m~/universal[00m$ python app.py
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Serving Flask app "app" (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://172.17.0.2:12345/ (Press CTRL+C to quit)
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
127.0.0.1 - - [02/Jul/2021 04:55:57] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 04:56:02] "[35m[1mGET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2127, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a Tensor.
127.0.0.1 - - [02/Jul/2021 04:56:05] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 04:56:07] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 04:56:09] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 04:56:10] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
 * Detected change in '/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py', reloading
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
 * Detected change in '/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py', reloading
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
 * Detected change in '/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py', reloading
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
^C(base) ]0;~/universal[01;34m~/universal[00m$ python app.py
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Serving Flask app "app" (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://172.17.0.2:12345/ (Press CTRL+C to quit)
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
127.0.0.1 - - [02/Jul/2021 10:33:10] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
DialoGPT1: What type of role do you want to take on after this one?
127.0.0.1 - - [02/Jul/2021 10:33:13] "[35m[1mGET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py", line 48, in get_bot2bot_response
    return respond_bot2bot()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py", line 107, in respond_bot2bot
    if question==0:
NameError: name 'question' is not defined
127.0.0.1 - - [02/Jul/2021 10:33:15] "[35m[1mGET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py", line 48, in get_bot2bot_response
    return respond_bot2bot()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py", line 96, in respond_bot2bot
    bot1_input = history
UnboundLocalError: local variable 'history' referenced before assignment
127.0.0.1 - - [02/Jul/2021 10:33:16] "[35m[1mGET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py", line 48, in get_bot2bot_response
    return respond_bot2bot()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py", line 96, in respond_bot2bot
    bot1_input = history
UnboundLocalError: local variable 'history' referenced before assignment
127.0.0.1 - - [02/Jul/2021 10:33:17] "[35m[1mGET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py", line 48, in get_bot2bot_response
    return respond_bot2bot()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py", line 96, in respond_bot2bot
    bot1_input = history
UnboundLocalError: local variable 'history' referenced before assignment
127.0.0.1 - - [02/Jul/2021 10:33:19] "[35m[1mGET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py", line 48, in get_bot2bot_response
    return respond_bot2bot()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py", line 96, in respond_bot2bot
    bot1_input = history
UnboundLocalError: local variable 'history' referenced before assignment
 * Detected change in '/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py", line 27, in <module>
    chat_hi
NameError: name 'chat_hi' is not defined
(base) ]0;~/universal[01;34m~/universal[00m$ python app.py
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Serving Flask app "app" (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://172.17.0.2:12345/ (Press CTRL+C to quit)
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
127.0.0.1 - - [02/Jul/2021 10:55:18] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 10:55:22] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 10:55:25] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 10:55:44] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
^C(base) ]0;~/universal[01;34m~/universal[00m$ python app.py
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Serving Flask app "app" (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://172.17.0.2:12345/ (Press CTRL+C to quit)
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
127.0.0.1 - - [02/Jul/2021 10:57:26] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 10:57:31] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 10:57:34] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 10:57:39] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 10:57:41] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 10:57:46] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 10:57:49] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 10:58:38] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 10:58:39] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 10:58:43] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 10:58:46] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 10:58:58] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 10:59:35] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 10:59:38] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 10:59:42] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 10:59:49] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 10:59:54] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 10:59:57] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:00:01] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
 * Detected change in '/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py', reloading
 * Restarting with stat
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py", line 63
    def reset()
              ^
SyntaxError: invalid syntax
(base) ]0;~/universal[01;34m~/universal[00m$ python app.py
  File "app.py", line 68
    global chat_history_bot2human = None
                                  ^
SyntaxError: invalid syntax
(base) ]0;~/universal[01;34m~/universal[00m$ python app.py
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Serving Flask app "app" (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://172.17.0.2:12345/ (Press CTRL+C to quit)
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
127.0.0.1 - - [02/Jul/2021 11:03:36] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:03:40] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:03:43] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:07:00] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:07:03] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:07:06] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:13:26] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:13:30] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:13:34] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:15:23] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:15:26] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:15:30] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:15:47] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:15:50] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:15:53] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:28:39] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:28:43] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:28:49] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:29:06] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:29:10] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:29:15] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:29:33] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:29:35] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:29:39] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:32:20] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:32:25] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/human2bot_get?msg=Hi HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:32:31] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/human2bot_get?msg=How+are+you+today%3F HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:32:37] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/human2bot_get?msg=I+am+very+good HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:32:56] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:33:00] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/human2bot_get?msg=Hi HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:33:13] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/human2bot_get?msg=We+are+good HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:33:15] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:33:19] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/human2bot_get?msg=Hi HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:33:23] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/human2bot_get?msg=I+am+good HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:33:28] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/human2bot_get?msg=Can+we+play+a+game HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:33:40] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/human2bot_get?msg=What+movies+do+you+like%3F HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:33:46] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/human2bot_get?msg=Can+we+go+out%3F HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:33:51] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/human2bot_get?msg=Stop HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:34:03] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:34:06] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:41:00] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:41:55] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:41:59] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:42:02] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:43:41] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:44:03] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:44:06] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:44:10] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:44:23] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:44:26] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:44:42] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:44:47] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:46:57] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:49:04] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:49:08] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:53:01] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:53:06] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:53:16] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:53:38] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:53:46] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
^C(base) ]0;~/universal[01;34m~/universal[00m$ python app.py
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Serving Flask app "app" (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://172.17.0.2:12345/ (Press CTRL+C to quit)
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
127.0.0.1 - - [02/Jul/2021 11:55:32] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:55:36] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:55:41] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:55:47] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:56:13] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:56:17] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:56:20] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 11:56:25] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
 * Detected change in '/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py', reloading
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
 * Detected change in '/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py', reloading
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
 * Detected change in '/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py', reloading
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
 * Detected change in '/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py', reloading
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
127.0.0.1 - - [02/Jul/2021 12:05:36] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:05:41] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:05:47] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
 * Detected change in '/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py', reloading
 * Restarting with stat
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py", line 49
    def reset
            ^
SyntaxError: invalid syntax
(base) ]0;~/universal[01;34m~/universal[00m$ python app.py
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Serving Flask app "app" (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://172.17.0.2:12345/ (Press CTRL+C to quit)
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
127.0.0.1 - - [02/Jul/2021 12:10:10] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:10:43] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:10:46] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:10:48] "[35m[1mGET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/reset HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
127.0.0.1 - - [02/Jul/2021 12:10:50] "[35m[1mGET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/reset HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
127.0.0.1 - - [02/Jul/2021 12:10:52] "[35m[1mGET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/reset HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
127.0.0.1 - - [02/Jul/2021 12:10:53] "[35m[1mGET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/reset HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
127.0.0.1 - - [02/Jul/2021 12:10:53] "[35m[1mGET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/reset HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
 * Detected change in '/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py', reloading
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
 * Detected change in '/projects/3e080ba6-1476-4b72-953b-1b591cbf600a/universal/app.py', reloading
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
127.0.0.1 - - [02/Jul/2021 12:11:49] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:11:53] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:11:58] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:12:02] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:12:05] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/reset HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:12:07] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/reset HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:12:07] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/reset HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:12:16] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/reset HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:12:16] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/reset HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:12:16] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/reset HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:13:33] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:13:56] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:14:02] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/reset HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:14:07] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:14:11] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/reset HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:14:16] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:14:57] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:15:01] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:15:05] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/reset HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:15:08] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/reset HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:15:50] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:15:52] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/reset HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:15:56] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:15:58] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/reset HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:16:09] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:16:12] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:16:14] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/reset HTTP/1.1" 200 -
^C(base) ]0;~/universal[01;34m~/universal[00m$ python app.py
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Serving Flask app "app" (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://172.17.0.2:12345/ (Press CTRL+C to quit)
 * Restarting with stat
Try to open

    https://cocalc3.ai-camp.org/3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/


 * Debugger is active!
 * Debugger PIN: 317-047-398
127.0.0.1 - - [02/Jul/2021 12:16:39] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:16:44] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:16:46] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/reset HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:18:24] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:18:27] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:18:28] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/reset HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:18:54] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:18:56] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:18:57] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/reset HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:18:59] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:19:02] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:19:04] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/reset HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:23:12] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:24:00] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:24:12] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:24:23] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:24:48] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:25:00] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/reset HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:25:43] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:25:47] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/human2bot_get?msg=Hello HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:25:51] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/human2bot_get?msg=Where+are+you%3F HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:25:54] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/human2bot_get?msg=Wow HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:26:02] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/human2bot_get?msg=Can+you+play+some+music%3F HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:26:09] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/human2bot_get?msg=Do+you+love+movies%3F HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:26:16] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/human2bot_get?msg=Which+movie+do+you+like%3F HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:26:24] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/human2bot_get?msg=Which+movie+do+you+like+the+best%3F HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:26:32] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:26:36] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/human2bot_get?msg=Which+movie+do+you+like+the+best%3F HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:26:45] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/human2bot_get?msg=Do+you+like+me%3F HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:26:50] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:26:54] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:26:57] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:27:01] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:27:07] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:27:14] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/bot2bot_get HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:28:48] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:28:52] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/reset HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:29:22] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:29:24] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/reset HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:29:27] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/human2bot_get?msg=Hi HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:29:31] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/human2bot_get?msg=How+are+you%3F HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:29:33] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/reset HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:29:44] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/human2bot_get?msg=Do+you+love+movies%3F HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:29:50] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/human2bot_get?msg=That%27s+so+cool. HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:29:57] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/human2bot_get?msg=How+do+you+do%3F HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:29:59] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/reset HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:30:04] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/human2bot_get?msg=How+do+you+do%3F HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:30:13] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/human2bot_get?msg=Do+you+watch+movies%3F HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2021 12:30:18] "GET /3e080ba6-1476-4b72-953b-1b591cbf600a/port/12345/reset HTTP/1.1" 200 -
